# This rule is not used by the project horizontalpodautoscalerx itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the autoscalingx.rrethy.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: horizontalpodautoscalerx
    app.kubernetes.io/managed-by: kustomize
  name: horizontalpodautoscalerx-editor-role
rules:
- apiGroups:
  - autoscalingx.rrethy.io
  resources:
  - horizontalpodautoscalerxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscalingx.rrethy.io
  resources:
  - horizontalpodautoscalerxes/status
  verbs:
  - get
