---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers/status
  verbs:
  - get
- apiGroups:
  - autoscalingx.rrethy.io
  resources:
  - horizontalpodautoscalerxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscalingx.rrethy.io
  resources:
  - horizontalpodautoscalerxes/finalizers
  verbs:
  - update
- apiGroups:
  - autoscalingx.rrethy.io
  resources:
  - horizontalpodautoscalerxes/status
  - hpaoverrides/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - autoscalingx.rrethy.io
  resources:
  - hpaoverrides
  verbs:
  - get
  - list
  - patch
  - update
  - watch
