apiVersion: autoscalingx.rrethy.io/v1
kind: HorizontalPodAutoscalerX
metadata:
  labels:
    app.kubernetes.io/name: horizontalpodautoscalerx
    app.kubernetes.io/managed-by: kustomize
  name: horizontalpodautoscalerx-sample
spec:
  hpaTargetName: myhpa
  fallback:
    minReplicas: 50
    duration: "120s"
  minReplicas: 10
